### ISSUE TITLE
Practica Grupal Podcast Devtech

### ISSUE THREAD

**Issue by josetejerina** [pablo182s/devtech-podcast-web#1]
Hola compañero, me sumo al proyecto de podcast devtech. Adjunto captura de mi perfil que estaré agregando. Saludos.
![image](https://user-images.githubusercontent.com/107653230/178334471-7c68ffe1-283f-4f0b-a013-227c9ee0b94e.png)

**Comment by pablo182s** [comment]
Gracias José. Saludos!!!
